GET http://localhost:3001/api/persons/
###
GET http://localhost:3001/api/persons/5e96d0635a0d9d3a886f49ba
###
DELETE http://localhost:3001/api/persons/5e96d0635a0d9d3a886f49ba
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Kitty person",
    "number": "000-1234567"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "name": "Dog person"
}
###
POST http://localhost:3001/api/persons/
content-type: application/json

{
    "number": "000-1234567"
}